The ``7-base_geometry`` module
======================

Using ``7-base_geometry``
-------------------

Import ``BaseGeometry``:

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

We are testing the area() method:

    case: area() exception
    >>> bg = BaseGeometry()
    >>> try:
    ...     print(bg.area())
    ... except Exception as e:
    ...     print("[{}] {}".format(e.__class__.__name__, e))
    [Exception] area() is not implemented

We are testing the integer_validator() method:

    case: basic test
    >>> bg = BaseGeometry()
    >>> bg.integer_validator('width', 10)
    >>> bg.integer_validator('height', 15)

    case: value is string
    >>> bg.integer_validator("name", "John")
    Traceback (most recent call last):
    ...
    TypeError: name must be an integer

    case: value is 0
    >>> bg.integer_validator("name", 0)
    Traceback (most recent call last):
    ...
    ValueError: name must be greater than 0

    case: value is negative
    >>> bg.integer_validator("name", -2)
    Traceback (most recent call last):
    ...
    ValueError: name must be greater than 0

    case: value is list
    >>> bg.integer_validator("name", [1, 2])
    Traceback (most recent call last):
    ...
    TypeError: name must be an integer

    case: value is tuple
    >>> bg.integer_validator("name", (1, 2))
    Traceback (most recent call last):
    ...
    TypeError: name must be an integer

    case: value is a dict
    >>> bg.integer_validator("name", {1, 2})
    Traceback (most recent call last):
    ...
    TypeError: name must be an integer

    case: value is None
    >>> bg.integer_validator("name", None)
    Traceback (most recent call last):
    ...
    TypeError: name must be an integer

    case: value is boolean
    >>> bg.integer_validator("name", True)
    Traceback (most recent call last):
    ...
    TypeError: name must be an integer

    case: missing 1 argument
    >>> bg.integer_validator("name")
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'

    case: no arguments
    >>> bg.integer_validator()
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
